name: 'OpenFGA CLI'
description: 'GitHub Action to install and use OpenFGA CLI'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}

inputs:
  command:
    description: 'Command to run with OpenFGA CLI'
    required: true

